---
- name: Install
  hosts: localhost
  strategy: free
  vars_files:
    - vars/default.yaml
    - "vars/{{ ansible_facts['hostname'] }}.yaml"
  tasks:
    - name: Install Starship (https://starship.rs/)
      ansible.builtin.homebrew:
        package: starship

    - name: Install Fish (https://fishshell.com)
      ansible.builtin.homebrew:
        package: fish

    - name: Install KICS (https://kics.checkmarx.net)
      ansible.builtin.homebrew:
        package: kics
        state: absent


- name: Configure'
  hosts: localhost
  vars_files:
    - vars/default.yaml
    - "vars/{{ ansible_facts['hostname'] }}.yaml"
  tasks:
    - name: Configure Starship
      ansible.builtin.template:
        src: etc/starship/starship.toml.template
        dest: ~/.config/starship.toml

    - name: Configure Fish
      ansible.builtin.copy:
        src: etc/fish/config.fish
        dest: ~/.config/fish/config.fish
    - name: Configure Fish completions for AWS
      ansible.builtin.copy:
        src: etc/fish/completions/aws.fish
        dest: ~/.config/fish/completions/aws.fish
    - name: Configure Fish completions for Docker
      ansible.builtin.copy:
        src: etc/fish/completions/docker.fish
        dest: ~/.config/fish/completions/docker.fish
    - name: Configure Fish completions for Openshift CLI
      ansible.builtin.copy:
        src: etc/fish/completions/oc.fish
        dest: ~/.config/fish/completions/oc.fish
    - name: Configure Fish completions for ROSA CLI
      ansible.builtin.copy:
        src: etc/fish/completions/rosa.fish
        dest: ~/.config/fish/completions/rosa.fish

    - name: Configure SSH
      when: __template__ is exists
      vars:
        __template__: "etc/ssh/{{ ansible_facts['hostname'] }}/ssh_config"
      ansible.builtin.copy:
        src: "etc/ssh/{{ ansible_facts['hostname'] }}/ssh_config"
        dest: ~/.ssh/config
        mode: '400'

    - name: Configure Bash Aliases
      ansible.builtin.template:
        src: etc/bash/bash_aliases
        dest: ~/.bash_aliases

    - name: Configure Vim
      ansible.builtin.template:
        src: etc/vim/vimrc
        dest: ~/.vimrc
