---
- name: Configure
  hosts: localhost
  vars_files:
    - vars/default.yaml
    - "vars/{{ ansible_facts['hostname'] }}.yaml"
  tasks:
    - name: Render Configs
      when: item.src is exists
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - src: etc/starship/starship.toml.template
          dest: ~/.config/starship.toml
        - src: etc/fish/config.fish.template
          dest: ~/.config/fish/config.fish

    - name: Copy Configs
      when: item.src is exists
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - src: etc/fish/completions/aws.fish
          dest: ~/.config/fish/completions/aws.fish
        - src: etc/fish/completions/docker.fish
          dest: ~/.config/fish/completions/docker.fish
        - src: etc/fish/completions/oc.fish
          dest: ~/.config/fish/completions/oc.fish
        - src: etc/fish/completions/rosa.fish
          dest: ~/.config/fish/completions/rosa.fish
        - src: etc/fish/functions/mkcd.fish
          dest: ~/.config/fish/functions/mkcd.fish
        - src: etc/fish/functions/kubeconfig-set-token.fish
          dest: ~/.config/fish/functions/kubeconfig-set-token.fish
        - src: etc/fish/functions/k8s-node-ip.fish
          dest: ~/.config/fish/functions/k8s-node-ip.fish
        - src: etc/fish/functions/k8s-node-ssh.fish
          dest: ~/.config/fish/functions/k8s-node-ssh.fish
        - src: etc/fish/functions/k8s-groups-of.fish
          dest: ~/.config/fish/functions/k8s-groups-of.fish
        - src: etc/fish/functions/vault-kv-walk.fish
          dest: ~/.config/fish/functions/vault-kv-walk.fish
        - src: etc/bash/bash_aliases
          dest: ~/.bash_aliases
        - src: etc/vim/vimrc
          dest: ~/.vimrc
        - src: etc/flake8/flake8
          dest: ~/.config/flake8
        - src: etc/mypy/config
          dest: ~/.config/mypy/config
        - src: etc/yapf/style
          dest: ~/.config/yapf/style
        - src: "etc/ssh/{{ ansible_facts['hostname'] }}/ssh_config"
          dest: ~/.ssh/config
          mode: '400'
