---
- name: Install
  hosts: localhost
  strategy: free
  vars_files:
    - vars/default.yaml
    - "vars/{{ ansible_facts['hostname'] }}.yaml"
  tasks:
    - name: Subscribe to Package Provider
      ansible.builtin.homebrew_tap:
        name: "{{ item }}"
        state: present
      loop:
        - hashicorp/tap

    - name: Install Packages
      ansible.builtin.package:
        package: "{{ item }}"
        state: present
      loop:
        - argocd
        - argocd-vault-plugin
        - eksctl
        - fish
        - gdbm
        - git
        - gnu-sed
        - gnupg
        - grep
        - groff
        - guile
        - hashicorp/tap/terraform
        - helm
        - htop
        - jq
        - kind
        - kubernetes-cli
        - kubeseal
        - kustomize
        - libiscsi
        - librdkafka
        - libserdes
        - lua@5.3
        - mpdecimal
        - nmap
        - node
        - parallel
        - qemu
        - rush-parallel
        - shellcheck
        - sqlite
        - starship
        - telnet
        - tmux
        - tree
        - vault
        - watch
        - yajl

    - name: Uninstall Packages
      ansible.builtin.package:
        package: "{{ item }}"
        state: absent
      loop:
        - kics
