---
- name: Install
  hosts: localhost
  vars_files:
    - vars/default.yaml
    - "vars/{{ ansible_facts['hostname'] }}.yaml"
  tasks:
    - name: Subscribe to Package Provider
      tags: brew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      loop:
        - hashicorp/tap

    - name: Install Packages
      tags: brew
      ansible.builtin.package:
        package: "{{ item }}"
        state: present
      loop:
        - argocd
        - argocd-vault-plugin
        - bash-completion
        - cookiecutter
        - mysql-client
        - eksctl
        - fish
        - gdbm
        - git
        - glab
        - gnu-sed
        - gnupg
        - grep
        - groff
        - guile
        - hashicorp/tap/terraform
        - helm
        - htop
        - jq
        - kind
        - kubernetes-cli
        - kubeseal
        - kustomize
        - libiscsi
        - librdkafka
        - libserdes
        - lua@5.3
        - mpdecimal
        - nmap
        - node
        - parallel
        - qemu
        - rush-parallel
        - rustup-init
        - shellcheck
        - sqlite
        - starship
        - telnet
        - terraform-docs
        - tmux
        - tree
        - vault
        - watch
        - yajl
        - yq

    - name: Uninstall Packages
      tags: brew
      ansible.builtin.package:
        package: "{{ item }}"
        state: absent
      loop:
        - kics

    - name: Install Kubernetes CLI plugins
      tags: krew
      block:
        - name: Install Krew
          ansible.builtin.shell: |
            set -eo pipefail; cd "$(mktemp -d)" &&
            OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
            ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
            KREW="krew-${OS}_${ARCH}" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
            tar zxvf "${KREW}.tar.gz" &&
            ./"${KREW}" install krew &&
            $HOME/.krew/bin/kubectl-krew update
          register: pkg_install_krew
          changed_when: pkg_install_krew.rc != 0

        - name: Install plugins with Krew
          ansible.builtin.command: "$HOME/.krew/bin/kubectl-krew install {{ item }}"
          loop:
            - access-matrix
            - ctx
            - neat
            - ns
            - stern
            - view-secret
          register: pkg_install_krew_plugins
          changed_when: pkg_install_krew_plugins.rc != 0

    - name: Install PyPi Packages
      tags: pip
      ansible.builtin.pip:
        extra_args: --user
        name:
          - ansible
          - ansible-lint
          - flake8
          - yapf
          - pip
          - mypy
          - pyyaml
          - pipenv
          - certifi

    # Install Go: https://go.dev/doc/install
    - name: Install Golang apps
      tags: go
      ansible.builtin.command: "go install {{ item }}"
      loop:
        - github.com/spf13/cobra-cli@latest
        - github.com/cosmtrek/air@latest
      register: pkg_install_go_apps
      changed_when: pkg_install_go_apps.rc != 0
