---
- name: Install
  hosts: localhost
  vars_files:
    - vars/default.yaml
  tasks:
    - name: Subscribe to Package Provider
      tags: brew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      loop: []

    - name: Install Homebrew Formulae
      tags: brew
      community.general.homebrew:
        state: present
        package:
          - argocd
          - bash-completion
          - docker-completion
          - docker-credential-helper
          - eksctl
          - fish
          - git
          - glab
          - gnu-sed
          - gnupg
          - grep
          - groff
          - guile
          - helm
          - htop
          - jq
          - kubernetes-cli
          - kustomize
          - lima
          - lua@5.3
          - mysql-client
          - nmap
          - node
          - parallel
          - python
          - python@3.12
          - ruby
          - rush-parallel
          - rustup-init
          - shellcheck
          - sqlite
          - starship
          - telnet
          - terraform-docs
          - tmux
          - tree
          - watch
          - yq
          - hugo
          - gh
          - pinentry
          - pinentry-mac

    - name: Install Homebrew Formulae (force)
      tags: brew
      community.general.homebrew:
        force_formula: true
        package:
          - docker

    - name: Install Homebrew Casks
      tags: brew
      community.general.homebrew_cask:
        name: "{{ item }}"
      loop:
        - font-fira-code
        - font-fira-code-nerd-font

    - name: Uninstall Homebrew Formulae
      tags: brew
      ansible.builtin.package:
        state: absent
        package:
          - gdbm
          - libiscsi
          - librdkafka
          - libserdes
          - kics
          - kind
          - ruby-install
          - chruby
          - yajl
          - pcre
          - dnsmasq
          - k3d
          - kubeseal
          - cookiecutter
          - qemu
          - skaffold
          - argocd-vault-plugin
          - replicatedhq/replicated/cli
          - maven

    # Install Go: https://go.dev/doc/install
    - name: Install Golang apps
      tags: go
      ansible.builtin.command: "go install {{ item }}"
      loop:
        - github.com/spf13/cobra-cli@latest
        - github.com/air-verse/air@latest
        - github.com/corneliusweig/rakkess@latest
        - github.com/mattn/goreman@latest
        - golang.org/x/tools/cmd/godoc@latest
        - golang.org/x/pkgsite/cmd/pkgsite@latest
        - github.com/cloudflare/cfssl/cmd/...@latest
        - github.com/jstemmer/go-junit-report@latest
        - github.com/norwoodj/helm-docs/cmd/helm-docs@latest
      register: pkg_install_go_apps
      changed_when: pkg_install_go_apps.rc != 0

    - name: Uninstall Golang apps
      tags: go
      ansible.builtin.command: "rm -f $(go env GOPATH)/bin/{{ item }}"
      loop:
        - goreman
        - godoc
      register: pkg_uninstall_go_apps
      changed_when: pkg_uninstall_go_apps.rc != 0

    - name: Install Kubernetes CLI plugins
      tags: krew
      block:
        - name: Install Krew
          ansible.builtin.shell: |
            set -eo pipefail; cd "$(mktemp -d)" &&
            OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
            ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
            KREW="krew-${OS}_${ARCH}" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
            tar zxvf "${KREW}.tar.gz" &&
            ./"${KREW}" install krew &&
            $HOME/.krew/bin/kubectl-krew update
          register: pkg_install_krew
          changed_when: pkg_install_krew.rc != 0

        - name: Install plugins with Krew
          ansible.builtin.command: "$HOME/.krew/bin/kubectl-krew install {{ item }}"
          loop:
            - access-matrix
            - ctx
            - explore
            - fuzzy
            - graph
            - klock
            - ktop
            - kubescape
            - neat
            - ns
            - rbac-tool
            - resource-capacity
            - score
            - sniff
            - status
            - stern
            - tree
            - view-secret
          register: pkg_install_krew_plugins
          changed_when: pkg_install_krew_plugins.rc != 0

        - name: Uninstall plugins with Krew
          ansible.builtin.command: "$HOME/.krew/bin/kubectl-krew uninstall {{ item }}"
          loop:
            - grep
            - warp
            - preflight
            - support-bundle
          ignore_errors: yes

        - name: Workaround for access-matrix
          block:
            - name: Delete original access-matrix binary
              ansible.builtin.file:
                path: ~/.krew/store/access-matrix/v0.5.0/access-matrix-arm64-darwin
                state: link
                force: true
                follow: false
                src: ~/go/bin/rakkess

    - name: Install Ruby gems
      tags:
        - ruby
        - gem
      community.general.gem:
        name: "{{ item }}"
      loop:
        - jekyll

    - name: Install Rust
      tags:
        - rust
      ansible.builtin.command:
        cmd: rustup-init -y
        creates: ~/.cargo/bin
