" Not in VSCode Vim
" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" File type detection
filetype on
filetype plugin on
filetype indent on

syntax enable

" Autocompletion
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Line numbers
set number
set relativenumber

" Indentation
set shiftwidth=4
set tabstop=4
set expandtab

" Do not save backup files.
set nobackup

" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap
set statusline=%f\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P

" VSCode Vim. Disabled settings are for Neovim, or we let Vim decide.
set autoindent
set nogdefault
set nohlsearch
set history=50
set ignorecase
set incsearch
" set inccommand replace
set joinspaces
set maxmapdepth=1000
set report=2
" set shell /bin/bash
set scroll=0
set showcmd
set showmode
" set showmodename
set smartcase
set startofline
set textwidth=80
" set timeout=1000
set whichwrap=b,s

" Custom keybindings
nnoremap <space> <nop>
let mapleader = " "
nmap <leader>q :q<cr>
nmap <leader>w :w<cr>
nmap <leader>s :split<cr>
nmap <leader>v :vsplit<cr>
nmap <leader>h <c-w>h<cr>
nmap <leader>j <c-w>j<cr>
nmap <leader>k <c-w>k<cr>
nmap <leader>l <c-w>l<cr>
nmap <leader><left> <c-w><left><cr>
nmap <leader><down> <c-w><down><cr>
nmap <leader><up> <c-w><up><cr>
nmap <leader><right> <c-w><right><cr>
imap jj <esc>
vnoremap < <gv
vnoremap > >gv
