" Not in VSCode Vim
" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" File type detection
filetype on
filetype plugin on
filetype indent on

syntax enable

" Autocompletion
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Line numbers
set number
set relativenumber

" Indentation
set shiftwidth=4
set tabstop=4
set expandtab

" Do not save backup files.
set nobackup

" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap
set statusline=%f\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P

" VSCode Vim. Disabled settings are for Neovim, or we let Vim decide.
set autoindent
set nogdefault
set nohlsearch
set history=50
set ignorecase
set incsearch
" set inccommand replace
set joinspaces
set maxmapdepth=1000
set report=2
" set shell /bin/bash
set scroll=0
set showcmd
set showmode
" set showmodename
set smartcase
set startofline
set textwidth=80
" set timeout=1000
set whichwrap=b,s

" Custom keybindings
" nnoremap <space> <nop>
let mapleader = " "
nnoremap <leader>s :split<cr>
nnoremap <leader>v :vsplit<cr>
nnoremap <leader>h <c-w>h<cr>
nnoremap <leader>j <c-w>j<cr>
nnoremap <leader>k <c-w>k<cr>
nnoremap <leader>l <c-w>l<cr>
nnoremap <leader><left> <c-w><left><cr>
nnoremap <leader><down> <c-w><down><cr>
nnoremap <leader><up> <c-w><up><cr>
nnoremap <leader><right> <c-w><right><cr>
inoremap jj <esc>
vnoremap < <gv
vnoremap > >gv

" Vim plugins
" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin()

" VSCode vim
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'michaeljsmith/vim-indent-object'
Plug 'bkad/CamelCaseMotion'
Plug 'vim-scripts/ReplaceWithRegister'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-user'
Plug 'wellle/targets.vim'

" TODO: continue later
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

call plug#end()

nnoremap <leader>N :NERDTreeToggle<cr>
nnoremap <leader>P :FZF -i<cr>
nnoremap <leader>R :source $MYVIMRC<cr>
