format = """
[┌─\

\\[\
$directory\

$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
\\]\

(\

────\\[\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$env_var\
$crystal\
$custom\
$singularity\

$docker_context\
$package\
\\]\

)\

(\

────\\[\
$kubernetes\
$aws\
$gcloud\
$openstack\
$azure\
$localip\
$sudo\
\\]\

)\

]()\

$line_break\

[└─\

(\
\\[\
$os\
$time\
$shlvl\
$cmd_duration\
$status\
\\]\
)\

──$character]()"""

# -----------------------------------------------------------------------------
# LEFT LANE
#

[directory]
fish_style_pwd_dir_length = 2

[git_branch]
truncation_length = 16
symbol = " "
format = '[$symbol$branch]($style)'

[git_commit]
tag_disabled = false
tag_symbol = ' 炙'
format = '[ $hash$tag]($style)'

[git_state]
format = '[: $state( $progress_current/$progress_total)]($style)'

[git_status]
format = '[( $ahead_behind)]($style)'
ahead = '⬆️'
behind = '⬇️'

# -----------------------------------------------------------------------------
# APP VERSIONS
#

[c]
symbol = " "
#style = "bg:powerline2"
format = '[$symbol($version)]($style)'

[docker_context]
disabled = false
symbol = " "
format = '[ $symbol($version)]($style)'

[elixir]
symbol = " "
format = '[$symbol($version)]($style)'

[elm]
symbol = " "
format = '[$symbol($version)]($style)'

[golang]
symbol = " "
format = '[$symbol($version)]($style)'

[haskell]
symbol = " "
format = '[$symbol($version)]($style)'

[java]
symbol = " "
format = '[$symbol($version)]($style)'

[julia]
symbol = " "
format = '[$symbol($version)]($style)'

[nodejs]
symbol = " "
format = '[$symbol($version)]($style)'

[nim]
symbol = " "
format = '[$symbol($version)]($style)'

[rust]
symbol = " "
format = '[$symbol($version)]($style)'

[scala]
symbol = " "
format = '[$symbol($version)]($style)'

[python]
symbol = " "
format = '[$symbol($version)(@$virtualenv)]($style)'

[terraform]
symbol = "󱁢 "
format = '[$symbol($version)]($style)'

[helm]
symbol = "󰠳 "
format = '[$symbol($version)]($style)'

[package]
disabled = false
format = '[ $symbol($version)]($style)'

# -----------------------------------------------------------------------------
# RIGHT LANE
#

[kubernetes]
disabled = false
format = '[$symbol$context(/$namespace)]($style) '

[aws]
format = '[$symbol($profile)(@$region)(\[$duration\])]($style) '

[localip]
format = '[$localipv4]($style)'
ssh_only = false
disabled = false

# -----------------------------------------------------------------------------
# INPUT LANE
#
[os]
disabled = false
format = '[$symbol]($style)'

[time]
disabled = false
time_format = '%Y-%m-%d %H:%M'
format = '[$time]($style)'

[shlvl]
format = '[ $symbol$shlvl]($style)'
disabled = false
symbol = ' '

[sudo]
format = "[ ${symbol}POWER USER]($style)"
symbol = '⚡️'
disabled = false

[cmd_duration]
format = '[ 󰾆 $duration]($style)'
show_milliseconds = true

[status]
format = '[ $symbol$status]($style)'
pipestatus_format = '[ $pipestatus  $common_meaning$signal_name$maybe_int]($style)'
pipestatus_segment_format = '$status'
symbol = ' '
disabled = false
pipestatus = true

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
format = '$symbol '

# -----------------------------------------------------------------------------
# MISCELLANEOUS
#

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
